config/routes.rb
# Bubberchan: an anonymous image board built on Rails
# Copyright (C) 2015  Mathew Francis Kirschbaum
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

Rails.application.routes.draw do
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post 'signup' => 'users#create'
  post 'newroot' => 'users#newroot'

  resources :posts, path: ':board' do
    resources :comments, path: 'c'
  end
end

app/controllers/welcome_controller.rb
# Bubberchan: an anonymous image board built on Rails
# Copyright (C) 2015  Mathew Francis Kirschbaum
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class WelcomeController < ApplicationController
  def index
    render :index
  end
end

app/helpers/welcome_helper.rb
# Bubberchan: an anonymous image board built on Rails
# Copyright (C) 2015  Mathew Francis Kirschbaum
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

module WelcomeHelper
end

app/views/welcome/index.html.erb
<%#
Bubberchan: an anonymous image board built on Rails
Copyright (C) 2015  Mathew Francis Kirschbaum

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
%>

<% title meta.index_page_name %>
<h1 id="pagetitle"><%= meta.site_title %></h1>
<h2 id="pagesubtitle"><%= meta.motd %></h2>

<% unless User.first %>
	<div id="createroot">
		<h3>Password for root</h3>
		<%= form_for :root, url: newroot_path do |f| %>
			<div class="input-container"><%= f.password_field :password %></div>
			<div class="input-container"><%= f.submit %></div>
		<% end %>
	</div>
<% end %>

<div id="boards">
	<% Board.find_each do |board| %>
		<%= link_to posts_path(board: board.shortname) + ": " + board.title, posts_path(board: board.shortname) %>
		<br>
	<% end %>
</div>

<% if logged_in? %>
	Hello, <%= current_user.username %>
	<br>
	<% if admin? %>
		<%= button_to "Admin", admin_root_path, method: :get, class: "button-link-in-list" %>
		<%= button_to "Log out", logout_path, method: :delete, class: "button-link-in-list" %>
		<div id="signup">
		<%= form_for :user, url: signup_path do |f| %>
			<div class="input-container inline"><%= f.text_field :username %></div>
			<div class="input-container inline"><%= f.password_field :password %></div>
			<div class="input-container inline"><%= f.submit %></div>
		<% end %>
		</div>
		<br>
	<% end %>
<% else %>
	<div id="login">
		<%= form_for :session, url: login_path do |f| %>
			<div class="input-container inline"><%= f.text_field :username %></div>
			<div class="input-container inline"><%= f.password_field :password %></div>
			<div class="input-container inline"><%= f.submit "Log In" %></div>
		<% end %>
	</div>
<% end %>