config/routes.rb
# Bubberchan: an anonymous image board built on Rails
# Copyright (C) 2015  Mathew Francis Kirschbaum
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

Rails.application.routes.draw do
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post 'signup' => 'users#create'
  post 'newroot' => 'users#newroot'

  resources :posts, path: ':board' do
    resources :comments, path: 'c'
  end
end

app/models/post.rb
# Bubberchan: an anonymous image board built on Rails
# Copyright (C) 2015  Mathew Francis Kirschbaum
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class Post < ActiveRecord::Base
  include ProcessedBody

  belongs_to :board
  has_many :comments

  mount_uploader :image, PostImageUploader

  before_save :process
end

app/controllers/admin/posts_controller.rb
# Bubberchan: an anonymous image board built on Rails
# Copyright (C) 2015  Mathew Francis Kirschbaum
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/posts_controller.rb
# Bubberchan: an anonymous image board built on Rails
# Copyright (C) 2015  Mathew Francis Kirschbaum
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class PostsController < ApplicationController
  before_action :validate_board

  def index
    render :index
  end

  def create
    post_params = params.require(:post).permit(:title, :body, :image)
    @new_post = Post.create(post_params.merge(board_id: @board.id))
    puts params.to_s
    redirect_to posts_path
  end

  def new
    render :new
  end

  def destroy
    Post.destroy(params[:id]) if admin?
    redirect_to posts_path
  end

  def show
    @post = Post.find_by id: params[:id], board_id: @board.id
    render :show
  end

  def edit
  end

  def update
  end
end

app/helpers/posts_helper.rb
# Bubberchan: an anonymous image board built on Rails
# Copyright (C) 2015  Mathew Francis Kirschbaum
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

module PostsHelper
end

app/views/posts/_form.html.erb
<%#
Bubberchan: an anonymous image board built on Rails
Copyright (C) 2015  Mathew Francis Kirschbaum

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
%>

<div id="newpost">
<%= form_for :post, url: posts_path do |f| %>
<br><br>
<table>
    <tr><td>
	    <%= f.label :title %>
    </td><td><div class="input-container">
	    <%= f.text_field :title %> <br><br>
    </div></td></tr><tr><td>
	    <%= f.label :body %>
    </td><td><div class="input-container">
	    <%= f.text_area :body %> <br><br>
    </div></td></tr><tr><td>
	    <%= f.label :image %>
    </td><td><div class="input-container">
	    <%= f.file_field :image, accept: "image/*" %> <br><br>
    </div></td></tr><tr><td></td><td><div class="input-container" id="post-submit-container">
	    <%= f.submit id: "post-submit" %>
    </div></td></tr>
</table>
<% end %>
</div>

app/views/posts/index.html.erb
<%#
Bubberchan: an anonymous image board built on Rails
Copyright (C) 2015  Mathew Francis Kirschbaum

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
%>

<% title "#{@board.title} | #{meta.site_title}" %>
<h1 id="pagetitle">/<%= @board.shortname %>/: <%= @board.title %></h1>
<h2 id="pagesubtitle"><%= @board.description %></h3>
<button id="formtoggle">New Post</button>
<%= render "form" %>
<hr>

<% Post.where(board_id: @board.id).reverse.each do |p| %>
  <h3><%= link_to p.title, post_full_path(p) %></h3>
  <p><%= escape p.body %></p>
  <%= link_to p.image.url do %>
  	<%= image_tag p.image.thumb.url %>
  <% end %>
  <% if admin? %>
  	<%= button_to "Delete post", post_full_path(p), method: :delete, data: {confirm: "Are you sure?"} %>
  <% end %>
  <hr>
<% end %>

app/views/posts/new.html.erb
<%#
Bubberchan: an anonymous image board built on Rails
Copyright (C) 2015  Mathew Francis Kirschbaum

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
%>

<% title "New Post | #{meta.site_title}" %>

<%= render "form" %>

app/views/posts/show.html.erb
<%#
Bubberchan: an anonymous image board built on Rails
Copyright (C) 2015  Mathew Francis Kirschbaum

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
%>

<% title "Post \##{@post.id} | #{meta.site_title}" %>

<h1 class="pagetitle"><%= @post.title %></h1>
<p class="main-content"><%= escape @post.body %></p>
<%= link_to @post.image.url do %>
	<%= image_tag @post.image.thumb.url %>
<% end %>
<hr>
<h3>New comment</h3>
<%= form_for :comment, url: post_comments_path(@post, board: @board.shortname) do |f| %>
	<div class="input-container"><%= f.text_area :body %></div>
	<div class="input-container"><%= f.submit %></div>
<% end %>
<hr>
<% @post.comments.reverse.each do |c| %>
	<p class="secondary-content"><%= escape c.body %></p>
	<% if admin? %>
		<%= button_to "Delete comment", post_comment_path(c, post_id: @post.id, board: @board.shortname), method: :delete, data: {confirm: "Are you sure?"} %>
	<% end %>
	<hr>
<% end %>